# Generated by Django 3.0 on 2019-12-05 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('interested_in', models.CharField(max_length=10)),
                ('astrological_sign', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('dater_name', models.CharField(max_length=55)),
                ('dater_email_address', models.CharField(max_length=55)),
                ('dater_telephone', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=55)),
                ('address_line_2', models.CharField(max_length=25, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('ethnicity', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=15)),
                ('looking_for', models.CharField(max_length=25)),
                ('has_children', models.BooleanField()),
                ('has_children_no', models.IntegerField(null=True)),
                ('education', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=15)),
                ('smokes', models.BooleanField()),
                ('smokes_vape', models.BooleanField(null=True)),
                ('dater_story', models.TextField()),
                ('dater_photo', models.ImageField(upload_to='')),
                ('pet_photo', models.ImageField(upload_to='')),
                ('pet_name', models.CharField(max_length=30)),
                ('pet_breed', models.CharField(max_length=30)),
                ('pet_color', models.CharField(max_length=20)),
                ('pet_age', models.IntegerField()),
                ('pet_story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Potential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potentials', to='PC.Dater')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
                ('created_date', models.DateField()),
                ('dater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='PC.Dater')),
                ('potential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='PC.Potential')),
            ],
        ),
    ]
